# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Charlie Kaminer Wrote Some Stuff
author: Charles Kaminer
email: cjkaminer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a New York City based software developer, currently working as an on-site 
  consultant for a large search company. Before moving to New York in May 2019 I
  was building out infrastructure on the Automation & Orchestration team for Allstate's
  Compozed Labs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cjkaminer
github_username:  ckaminer

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - 2019-04-05-welcome-to-jekyll.md
